title: Connor Hanan
logo: /headshot_small.jpg
description: Devoted my heart to PowerBI! Crafting dashboards, leveraging Python, adept at SQL querying, Excel automation mastery. 🚀 
projects: google_capstone.ipynb
#show_downloads: true
theme: jekyll-theme-minimal
