title: Connor Hanan
logo: Headshot small.jpeg
description: Devoted my heart to PowerBI! Crafting dashboards, leveraging Python, adept at SQL querying, Excel automation mastery. 🚀 
#show_downloads: true
theme: jekyll-theme-minimal
